version: '3.9'
services:
  redis-node-1:
    image: redis:6.2
    container_name: redis-node-1
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7001:7001"
      - "17001:17001" # クラスタ通信用ポート
    volumes:
      - ./redis/node-1:/usr/local/etc/redis
    networks:
      - redis-cluster

  redis-node-2:
    image: redis:6.2
    container_name: redis-node-2
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7002:7002"
      - "17002:17002"
    volumes:
      - ./redis/node-2:/usr/local/etc/redis
    networks:
      - redis-cluster

  redis-node-3:
    image: redis:6.2
    container_name: redis-node-3
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "7003:7003"
      - "17003:17003"
    volumes:
      - ./redis/node-3:/usr/local/etc/redis
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge
